### ISSUE TITLE
Running the examples as directed fails with an error.

### ISSUE THREAD

**Issue by duncanguthrie** [ukcp-data/ukcp-api-client#1]
Hi,

I tried running the examples as the introductory readme file suggests.
I've encountered the following error and wasn't really sure how to proceed.
I've had good success requesting data via the web interface.

Any input would be appreciated.

```
Traceback (most recent call last):
  File "examples/run_1_request.py", line 1, in <module>
    from ukcp_api_client.client import UKCPApiClient
ImportError: No module named ukcp_api_client.client
```

**Comment by agstephens** [comment]
Hi @duncanguthrie, thanks for trying out the library. I have updated the README (https://github.com/ukcp-data/ukcp-api-client/blob/master/README.md) with the line:

```
export PYTHONPATH=.:$PYTHONPATH
```

Please re-try. If it doesn't work please can you provide the output of the command: `pip freeze`

Thanks
